In [1]:
import pandas as pd

# Ejercicio 1

Trabajas como analista para una plataforma de vídeo. Tienes los datos de visualizaciones de la semana. Debes:

Filtrar el DataFrame para mostrar solo las Series que tengan entre 15 y 50 millones de visualizaciones 
Agrupar los datos por Género, calcular el total de visualizaciones de cada uno y ordenar el resultado de mayor a menor.

datos_streaming = {
    'Título': ['Stranger Things', 'Inception', 'The Crown', 'Avengers', 'Dark', 'Interstellar', 'The Boys'],
    'Tipo': ['Serie', 'Película', 'Serie', 'Película', 'Serie', 'Película', 'Serie'],
    'Género': ['Sci-Fi', 'Sci-Fi', 'Drama', 'Acción', 'Sci-Fi', 'Sci-Fi', 'Acción'],
    'Visualizaciones': [65, 40, 25, 80, 18, 55, 45]
}

df_streaming = pd.DataFrame(datos)
def_streaming

In [6]:
datos_streaming = {
    'Título': ['Stranger Things', 'Inception', 'The Crown', 'Avengers', 'Dark', 'Interstellar', 'The Boys'],
    'Tipo': ['Serie', 'Película', 'Serie', 'Película', 'Serie', 'Película', 'Serie'],
    'Género': ['Sci-Fi', 'Sci-Fi', 'Drama', 'Acción', 'Sci-Fi', 'Sci-Fi', 'Acción'],
    'Visualizaciones': [65, 40, 25, 80, 18, 55, 45]
}

df_visualizaciones = pd.DataFrame(datos_streaming)
df_visualizaciones

            Título      Tipo  Género  Visualizaciones
0  Stranger Things     Serie  Sci-Fi               65
1        Inception  Película  Sci-Fi               40
2        The Crown     Serie   Drama               25
3         Avengers  Película  Acción               80
4             Dark     Serie  Sci-Fi               18
5     Interstellar  Película  Sci-Fi               55
6         The Boys     Serie  Acción               45

In [9]:
# Filtrar el DataFrame para mostrar solo las Series que tengan entre 15 y 50 millones de visualizaciones

visualizaciones_15_50 = df_visualizaciones[(df_visualizaciones['Tipo']== 'Serie') & df_visualizaciones['Visualizaciones'].between(15, 50)]

visualizaciones_15_50

      Título   Tipo  Género  Visualizaciones
2  The Crown  Serie   Drama               25
4       Dark  Serie  Sci-Fi               18
6   The Boys  Serie  Acción               45

Agrupar los datos por Género, calcular el total de visualizaciones de cada uno y ordenar el resultado de mayor a menor.

In [12]:
# reset_index() genera la visualizacion en formato tabla y un dataframe para poder volver a usar despues
# 
visualizaciones_genero = df_visualizaciones.groupby('Género')['Visualizaciones'].sum().reset_index()
display('Visualización por genero', visualizaciones_genero)

'Visualización por genero'

   Género  Visualizaciones
0  Acción              125
1   Drama               25
2  Sci-Fi              178

ordenar resultado mayor a menor

In [13]:
order_desc = visualizaciones_genero.sort_values(by='Visualizaciones', ascending=True)
order_desc

   Género  Visualizaciones
1   Drama               25
0  Acción              125
2  Sci-Fi              178